version: '3'

services:

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=testdb
    ports:
      - 3306:3306

  money-app:
    image: money-transfer-app
    restart: on-failure
    depends_on:
      - mysqldb
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysqldb
      - DATABASE_USER=root
      - DATABASE_PASSWORD=secret
      - DATABASE_NAME=testdb
      - DATABASE_PORT=3306